inherit_from:
- https://relaxed.ruby.style/rubocop.yml

Style/MixinUsage:
  Enabled: true
  Exclude: 
    - test/dummy/bin/**/*

Style/ClassVars:
  Enabled: true
  Exclude:
    - lib/slackify/handlers/base.rb

AllCops:
  TargetRubyVersion: 2.6
