language: ruby
rvm:
 - 2.5.1

before_install:
  - "gem update --system"
  - "gem install bundler"

install:
  - bundle install

jobs:  
  include:
    - stage: "Tests + Linting"
      name: "Linting"
      script: bundle exec rubocop
    - script: bundle exec rake   
      name: "Tests"
